export const SELECTION__SET_SELECTED_PROFILE = 'SELECTION__SET_SELECTED_PROFILE';
export const SELECTION__SET_SELECTED_PROFILES = 'SELECTION__SET_SELECTED_PROFILES';
export const SELECTION__SET_SELECTED_SIGNATURE = 'SELECTION__SET_SELECTED_SIGNATURE';
export const SELECTION__SET_SELECTED_SIGNATURES = 'SELECTION__SET_SELECTED_SIGNATURES';
